{% set name = "pybtex-docutils" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d53aa0c31dc94d61fd30ea3f06c749e6f510f9ff0e78cb2765a9300f173d8626

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - docutils >=0.8
    - pybtex >=0.16

test:
  commands:
    - python -c "import pybtex.plugin; pybtex.plugin.find_plugin('pybtex.backends', 'docutils')()"

about:
  home: https://github.com/mcmtroffaes/pybtex-docutils
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: A docutils backend for pybtex.
  description: A docutils backend for pybtex.
  doc_url: http://pybtex-docutils.readthedocs.org/
  dev_url: https://github.com/mcmtroffaes/pybtex-docutils

extra:
  recipe-maintainers:
    - croth1
